general:

    # The amount of sandboxes to create for each language when the system starts up.
    start_amount: 2

    # The maximum amount of sandbox to create for each language. It won't create more than this amount of sandboxes, even if the load is high.
    scale_limit: 5

    # The amount of seconds to wait before killing a sandbox that is idle. A sandbox is idle if it has no running processes and no files have been created or modified in the last X seconds.
    idle_timeout: 300

    # The amount of seconds to wait before killing a sandbox that is running a process. A sandbox is running if it has at least one process that is still running after the timeout.
    running_timeout: 60

# TODO: Create language specific configurations.


